id: P6EE98736
initial_creation_type: input
source_metadata:
  title: Rogza Sönam Palge
  language: bo
  description: 'Texts by and about Rogza Sönam Palge (rog bza'' bsod nams dpal dge,
    1800–1884):'
  volume:
    3892744a139048f8be7bba574bef1d34:
      title: In Praise of Sönam Palge
      parent: Praise
created_at: '2022-03-01T01:23:33.772540'
last_modified_at: '2022-03-01T01:23:33.772542'
statistics:
  total_words: 417
  total_non_words: 40
quality:
  non_words_ratio: 0.1
